import { Boxes, LockKeyhole, Server, ShieldCheck, Workflow } from 'lucide-react';
import { CodeBlock } from '../components/CodeBlock';
import { PageHeader } from '../components/PageHeader';
import { Panel } from '../components/Panel';
export function ArchitecturePage(){return <>
  <PageHeader title="Arquitetura e API" description="Separação entre interface não privilegiada e backend executor controlado." />
  <div className="architecture-flow"><div><Boxes/><strong>React / TypeScript</strong><span>HTTPS + JSON</span></div><span>→</span><div><ShieldCheck/><strong>API REST v1</strong><span>Auth, RBAC, CSRF, validação</span></div><span>→</span><div><Workflow/><strong>Orquestrador de tarefas</strong><span>Lock, backup, diff, rollback</span></div><span>→</span><div><Server/><strong>Adaptadores FreeBSD</strong><span>Samba, UFS, CUPS, syslog</span></div></div>
  <Panel title="Princípios de segurança" subtitle="O navegador nunca recebe privilégios do sistema"><div className="check-grid"><div className="check-card"><LockKeyhole/><strong>Sem shell no cliente</strong><p>A API recebe objetos tipados e escolhe operações predefinidas.</p></div><div className="check-card"><ShieldCheck/><strong>Allowlist</strong><p>Caminhos, arquivos, serviços e parâmetros permitidos são enumerados no backend.</p></div><div className="check-card"><Workflow/><strong>Transação operacional</strong><p>Toda alteração gera validação, diff, impacto, backup, execução, teste e auditoria.</p></div></div></Panel>
  <Panel title="Endpoints previstos" subtitle="Contratos versionados e idempotência para operações críticas"><CodeBlock>{`GET  /api/v1/system\nGET  /api/v1/filesystems\nGET  /api/v1/samba\nGET  /api/v1/cups\nPOST /api/v1/acl/conversion/simulate\nGET  /api/v1/shares\nPOST /api/v1/shares/preview\nPOST /api/v1/shares\nGET  /api/v1/principals\nPOST /api/v1/domain/test\nGET  /api/v1/printers\nGET  /api/v1/print-drivers\nGET  /api/v1/dfs\nGET  /api/v1/quotas\nGET  /api/v1/audit\nGET  /api/v1/services\nPOST /api/v1/services/{id}/action\nGET  /api/v1/jobs\nPOST /api/v1/jobs/{id}/rollback`}</CodeBlock></Panel>
  <Panel title="RBAC proposto" subtitle="Separação entre leitura, operação e administração"><div className="table-scroll"><table><thead><tr><th>Perfil</th><th>Escopo</th></tr></thead><tbody><tr><td>Auditor</td><td>Leitura de configuração, tarefas, eventos e relatórios.</td></tr><tr><td>Operador de arquivos</td><td>Operações restritas nos volumes autorizados.</td></tr><tr><td>Operador de impressão</td><td>Filas, trabalhos e drivers aprovados.</td></tr><tr><td>Administrador Samba</td><td>Compartilhamentos, ACLs, domínio membro e DFS.</td></tr><tr><td>Administrador do sistema</td><td>Montagens, quotas, serviços e arquivos de configuração.</td></tr><tr><td>Administrador de segurança</td><td>RBAC, auditoria, logs, certificados e políticas.</td></tr></tbody></table></div></Panel>
</>}
