import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, BarChart3 } from 'lucide-react';
import { api } from '../api/client';
import { READ_ONLY_RELEASE_REASON } from '../capabilities';
import { ErrorState, Loading } from '../components/Loading';
import { PageHeader } from '../components/PageHeader';
import { Panel } from '../components/Panel';
import { StatusBadge } from '../components/StatusBadge';
export function AuditPage(){const q=useQuery({queryKey:['audit'],queryFn:api.audit});if(q.isLoading)return <Loading/>;if(q.error)return <ErrorState error={q.error} message="Falha ao consultar a auditoria."/>;if(!q.data)return <ErrorState message="A API não retornou eventos de auditoria."/>;return <>
  <PageHeader title="Auditoria dos compartilhamentos" description="Perfis baseados em vfs_full_audit, condicionados à sintaxe e disponibilidade da versão instalada." />
  <Panel title="Perfil de auditoria" subtitle={READ_ONLY_RELEASE_REASON}><fieldset disabled><div className="form-grid"><label>Compartilhamento<select><option>Compartilhamento detectado</option></select></label><label>Perfil<select defaultValue="security"><option value="minimum">Mínimo</option><option value="security">Segurança</option><option value="changes">Alterações</option><option value="complete">Completo</option><option value="custom">Personalizado</option></select></label></div><div className="checkbox-grid">{['criação','abertura','leitura','gravação','fechamento','renomeação','exclusão','mkdir/rmdir','alteração de proprietário','alteração de ACL','falhas de acesso','operações administrativas'].map((e)=><label className="check-label" key={e}><input type="checkbox" defaultChecked={['criação','gravação','renomeação','exclusão','alteração de ACL','falhas de acesso'].includes(e)}/>{e}</label>)}</div></fieldset><div className="alert alert-warning"><AlertTriangle size={18}/> Alterações no perfil e estimativas operacionais permanecem bloqueadas nesta release.</div><button className="button" disabled title={READ_ONLY_RELEASE_REASON}><BarChart3 size={16}/> Testar formato e estimar volume</button></Panel>
  <Panel title="Eventos recentes" subtitle="Cada registro inclui identificador de correlação"><div className="table-scroll"><table><thead><tr><th>Data</th><th>Servidor/Share</th><th>Identidade</th><th>Cliente</th><th>Operação</th><th>Resultado</th><th>Objeto</th><th>Correlação</th></tr></thead><tbody>{q.data!.map((e)=><tr key={e.id}><td>{new Date(e.timestamp).toLocaleString('pt-BR')}</td><td>{e.server}<br/><strong>{e.share}</strong></td><td>{e.domain}\\{e.user}</td><td>{e.client}<br/><code>{e.ip}</code></td><td><code>{e.operation}</code></td><td><StatusBadge state={e.result==='success'?'success':'failed'}/></td><td><code>{e.path}</code></td><td><code>{e.correlationId}</code></td></tr>)}</tbody></table></div></Panel>
</>}
